import Foundation

/// The metabolic journeys players follow, step by step, through the body.
enum Library {
    static let pathways: [Pathway] = [
        breadToBrain, fiberParty, longChainBus, mctExpress, proteinPuzzle, tryptophanToMelatonin,
        tyrosineSuperstars, thyroidFire, cholesterolFamily, sunshineVitaminD, ironMission, insulinFromFood, atpPowerPlant,
    ]

    static func pathways(featuring id: String) -> [Pathway] {
        pathways.filter { $0.steps.contains { $0.star == id } }
    }

    static func pathways(visiting location: BodyLocation) -> [Pathway] {
        pathways.filter { $0.steps.contains { $0.location == location } }
    }

    // MARK: - Carbohydrates

    static let breadToBrain = Pathway(
        id: "bread-to-brain", title: "From Bread to Brain Power",
        subtitle: "Starch → Glucose → ATP", family: .carbs, emoji: "🍞",
        steps: [
            PathwayStep(.mouth, "starch", "Crunch time!",
                        "Stella Starch enters the mouth inside a slice of bread. Teeth crush her into small pieces while saliva washes over her.",
                        ["Teeth 🦷", "Saliva 💧"]),
            PathwayStep(.mouth, "amylase", "Snip, snip!",
                        "Amy Amylase from your saliva starts cutting the alpha bonds between Stella's glucose beads. That's why bread tastes sweeter the longer you chew!",
                        ["Salivary amylase ✂️"]),
            PathwayStep(.stomach, "starch", "Acid bath pause",
                        "In the stomach, strong acid switches Amy off. Stella gets churned into a soupy mix called chyme and waits for the next stop.",
                        ["Stomach acid (HCl) 🧪"]),
            PathwayStep(.smallIntestine, "maltose", "Pancreas to the rescue",
                        "The pancreas squirts in more amylase plus bicarbonate to calm the acid. Stella is chopped into pairs of glucose called maltose. Meet the twins, Molly & Mal!",
                        ["Pancreatic amylase ✂️", "Bicarbonate 🫧"]),
            PathwayStep(.smallIntestine, "glucose", "Twins split up",
                        "Maltase enzymes on the gut wall split each maltose into two glucose. Gus Glucose hops through a door called SGLT1, pulled in together with sodium.",
                        ["Maltase ✂️", "SGLT1 door 🚪", "Sodium 🧂"]),
            PathwayStep(.bloodstream, "glucose", "Into the blood",
                        "Gus travels through the portal vein to the liver, then out into the bloodstream. Blood sugar rises, and the pancreas notices!",
                        ["Portal vein 🛣️"]),
            PathwayStep(.pancreas, "insulin", "The key master",
                        "Beta cells in the pancreas release Izzy Insulin. She travels through the blood, unlocking cells so glucose can get in.",
                        ["Zinc (insulin storage) 🛡️", "Calcium signal 🦴"]),
            PathwayStep(.liver, "glycogen", "Saving for later",
                        "Extra glucose is linked into Glenn Glycogen, a branchy storage tree in the liver and muscles. Between meals, Glenn releases glucose to keep blood sugar steady.",
                        ["Insulin 🔑", "Glycogen synthase 🌳"]),
            PathwayStep(.cell, "pyruvate", "Glycolysis split",
                        "Inside a cell, Gus is split in half through 10 steps called glycolysis. One glucose becomes two Pip Pyruvates, plus 2 ATP and 2 NADH.",
                        ["Magnesium 🌿", "Vitamin B3 (NAD⁺) 🔥"]),
            PathwayStep(.mitochondria, "acetylcoa", "Enter the powerhouse",
                        "Pip slips into a mitochondrion and loses one carbon as CO₂, which you breathe out! What's left becomes Acey Acetyl-CoA.",
                        ["Vitamin B1 (thiamine)", "Vitamin B2", "Vitamin B3", "Vitamin B5 (CoA)"]),
            PathwayStep(.mitochondria, "atp", "Power up!",
                        "Acey spins through the Krebs cycle and the electron transport chain. In the end, one glucose makes about 30 to 32 ATP: energy for thinking, running and growing!",
                        ["Oxygen 💨", "Iron 🧲", "Copper 🪙", "Magnesium 🌿"]),
        ],
        check: QuizQuestion("Why does bread taste sweeter the longer you chew it?",
                            "Amylase in saliva cuts starch into sugars",
                            ["Teeth turn bread into honey", "Saliva is full of sugar", "Bread turns into protein"],
                            "Salivary amylase snips starch's alpha bonds, releasing sweet maltose."))

    static let fiberParty = Pathway(
        id: "fiber-party", title: "Fiber's Secret Party",
        subtitle: "Fiber → Microbes → Short-chain fats", family: .carbs, emoji: "🥦",
        steps: [
            PathwayStep(.mouth, "fiber", "Unbreakable bonds",
                        "Fiona Fiber arrives in a crunchy apple. Amylase tries to cut her, but her beta bonds don't fit human enzymes. Fiona just smiles.",
                        ["Teeth 🦷"]),
            PathwayStep(.stomach, "fiber", "Slow and full",
                        "Soluble fiber soaks up water and forms a gel. It slows digestion, so sugar enters the blood more gently and you feel full longer.",
                        ["Water 💧"]),
            PathwayStep(.smallIntestine, "fiber", "Just passing through",
                        "Starch, fats and proteins get absorbed here, but Fiona passes by untouched. She's heading somewhere special..."),
            PathwayStep(.largeIntestine, "microbe", "Microbe city",
                        "In the large intestine, trillions of microbes like Mo are waiting. They have the enzymes humans lack, and they ferment Fiona for food.",
                        ["Gut bacteria 🦠", "Microbe enzymes ✂️"]),
            PathwayStep(.largeIntestine, "butyrate", "Short-chain fats are born",
                        "Fermentation makes short-chain fatty acids: acetate (2 carbons), propionate (3) and Buddy Butyrate (4). Buddy is the colon cells' favorite fuel!",
                        ["Fermentation 🫧"]),
            PathwayStep(.liver, "butyrate", "Messages across the body",
                        "Buddy's cousin propionate travels to the liver to help make glucose, and acetate reaches the rest of the body. Short-chain fats also help keep the gut wall strong and calm.",
                        ["Portal vein 🛣️"]),
        ],
        check: QuizQuestion("Who digests fiber in your body?",
                            "Gut microbes in the large intestine",
                            ["Salivary amylase", "Stomach acid", "Pepsin"],
                            "Human enzymes can't cut fiber's beta bonds, but gut microbes can, and they make short-chain fatty acids."))

    // MARK: - Fats

    static let longChainBus = Pathway(
        id: "long-chain-bus", title: "The Long-Chain Bus Ride",
        subtitle: "Triglyceride → Chylomicron → ATP", family: .fats, emoji: "🚌",
        steps: [
            PathwayStep(.mouth, "lct", "Oily arrival",
                        "Lars Long-Chain rolls in with olive oil. He's a triglyceride: a glycerol backbone with three long fatty-acid tails. A tiny bit of tongue lipase gets to work.",
                        ["Lingual lipase 🪚"]),
            PathwayStep(.stomach, "lct", "Droplet churn",
                        "The stomach churns Lars into droplets while gastric lipase trims a few tails. Fat slows the stomach down, which is why fatty meals keep you full.",
                        ["Gastric lipase 🪚"]),
            PathwayStep(.smallIntestine, "bile", "Soap time!",
                        "The gallbladder squeezes out Billie Bile. Like dish soap, she breaks big fat globs into tiny droplets, giving enzymes more surface to work on.",
                        ["Gallbladder 💚", "Bile salts 🧼"]),
            PathwayStep(.smallIntestine, "lipase", "Snip the tails",
                        "Lippy Lipase from the pancreas, with her sidekick colipase, cuts two tails off each triglyceride. Lars is now 2 free fatty acids plus 1 monoglyceride.",
                        ["Pancreatic lipase 🪚", "Colipase 🤝"]),
            PathwayStep(.smallIntestine, "micelle", "Bubble ferry",
                        "The pieces hide inside Mimi Micelle, a tiny bubble with an oily core. She ferries them, plus vitamins A, D, E and K, to the gut wall.",
                        ["Bile salts 🧼", "Vitamins A, D, E, K 🥕"]),
            PathwayStep(.lymph, "chylomicron", "Board the bus!",
                        "Inside gut cells, the pieces are rebuilt into triglycerides and packed into Chuck Chylomicron. Chuck is too big for blood capillaries, so he enters the lymph vessels.",
                        ["Protein coat (ApoB-48) 🧥"]),
            PathwayStep(.bloodstream, "chylomicron", "Unloading stops",
                        "The lymph empties Chuck into the blood near the heart. On blood vessel walls, lipoprotein lipase unloads fatty acids into muscles and fat tissue.",
                        ["Lipoprotein lipase 🪚"]),
            PathwayStep(.mitochondria, "carnitine", "Taxi to the powerhouse",
                        "Long fatty acids can't enter mitochondria alone. Carly Carnitine drives them across the inner membrane.",
                        ["Carnitine 🚕"]),
            PathwayStep(.mitochondria, "acetylcoa", "Two carbons at a time",
                        "Beta-oxidation chops the fatty acid two carbons at a time into Acey Acetyl-CoA. One 16-carbon palmitate can make over 100 ATP!",
                        ["Vitamin B2 (FAD)", "Vitamin B3 (NAD⁺)", "Vitamin B5 (CoA)"]),
        ],
        check: QuizQuestion("Why do long-chain fats travel in the lymph first?",
                            "Chylomicrons are too big for blood capillaries",
                            ["Lymph is warmer than blood", "Fats dissolve easily in water", "The liver blocks them"],
                            "Chylomicrons are huge, so they enter the lymph and join the blood near the heart."))

    static let mctExpress = Pathway(
        id: "mct-express", title: "The MCT Express Lane",
        subtitle: "MCT → Portal vein → Ketones", family: .fats, emoji: "🏎️",
        steps: [
            PathwayStep(.mouth, "mct", "Short tails, fast track",
                        "Mia MCT arrives in coconut oil. Her fatty-acid tails are only 6 to 12 carbons long, much shorter than Lars Long-Chain's."),
            PathwayStep(.smallIntestine, "mct", "Quick snip",
                        "Lipase snips Mia quickly. Her medium-chain fatty acids mix with water fairly well, so they barely need bile or micelles.",
                        ["Pancreatic lipase 🪚"]),
            PathwayStep(.liver, "mct", "Express lane!",
                        "Instead of boarding the chylomicron bus, Mia's fatty acids zoom straight into the portal vein and arrive at the liver fast.",
                        ["Portal vein 🛣️", "Albumin taxi 🚖"]),
            PathwayStep(.mitochondria, "mct", "No taxi needed",
                        "Medium-chain fatty acids can slip into liver mitochondria without Carly Carnitine's taxi, so they're burned quickly.",
                        ["Beta-oxidation ⚙️"]),
            PathwayStep(.liver, "ketone", "Ketone factory",
                        "So much acetyl-CoA forms so fast that the liver turns the extra into Kip Ketone.",
                        ["Acetyl-CoA 🔀"]),
            PathwayStep(.brain, "ketone", "Fuel for the brain",
                        "Kip travels in the blood to the brain, heart and muscles, where he's turned back into acetyl-CoA to make ATP. A handy backup fuel when glucose is low!",
                        ["Blood 🩸"]),
        ],
        check: QuizQuestion("How do MCT fats reach the liver?",
                            "Straight through the portal vein",
                            ["Riding chylomicrons in the lymph", "Through the kidneys", "They never leave the stomach"],
                            "Medium-chain fatty acids skip the lymph and go directly to the liver through the portal vein."))

    // MARK: - Proteins

    static let proteinPuzzle = Pathway(
        id: "protein-puzzle", title: "Protein Puzzle: Break & Build",
        subtitle: "Protein → Amino acids → New proteins", family: .proteins, emoji: "🧶",
        steps: [
            PathwayStep(.mouth, "protein", "Tangled arrival",
                        "Pro Tein arrives in an egg. He's a long chain of amino acids folded into a tangle. Chewing breaks the food up, but saliva has no protein-cutting enzymes.",
                        ["Teeth 🦷"]),
            PathwayStep(.stomach, "pepsin", "Acid unfolds, pepsin chops",
                        "Stomach acid unfolds Pro, a bit like how cooking changes an egg. Then Pepper Pepsin chops the long chain into shorter pieces called peptides.",
                        ["Stomach acid (HCl) 🧪", "Pepsin 🥊"]),
            PathwayStep(.smallIntestine, "trypsin", "Pancreas power",
                        "The pancreas sends Tracy Trypsin and her partner chymotrypsin. They slice the peptides into even smaller pieces.",
                        ["Trypsin 🦀", "Chymotrypsin ✂️", "Bicarbonate 🫧"]),
            PathwayStep(.smallIntestine, "aminoacid", "Single beads",
                        "Enzymes on the gut wall finish the job. Ami Amino and friends are absorbed as single amino acids and tiny 2 to 3 bead peptides.",
                        ["Peptidases ✂️", "Amino acid doors 🚪"]),
            PathwayStep(.liver, "aminoacid", "Liver sorting center",
                        "In the liver, amino acids are sorted. Vitamin B6 helps swap amino groups to make the non-essential amino acids. The 9 essential ones must come from food!",
                        ["Vitamin B6 🔧"]),
            PathwayStep(.cell, "ribosome", "Build something new!",
                        "In a cell, Ribby Ribosome reads an mRNA recipe copied from DNA and links amino acids in the right order. Out come enzymes, muscle fibers, antibodies and more.",
                        ["mRNA recipe 📜", "Magnesium 🌿", "Energy (GTP & ATP) 🔋"]),
            PathwayStep(.muscle, "leucine", "Muscle switch",
                        "Leo Leucine flips a switch called mTOR that tells muscle cells: build protein now! Exercise plus protein makes muscles stronger.",
                        ["mTOR switch 💡"]),
            PathwayStep(.kidney, "urea", "Cleanup crew",
                        "Amino acids not needed for building can be burned for energy. Their nitrogen becomes toxic ammonia, which the liver turns into Yuri Urea. The kidneys flush him out.",
                        ["Urea cycle (liver) ♻️"]),
        ],
        check: QuizQuestion("What does stomach acid do to proteins?",
                            "Unfolds them so enzymes can cut them",
                            ["Turns them into sugar", "Makes them longer", "Absorbs them into the blood"],
                            "Acid denatures (unfolds) proteins so pepsin can reach and cut their bonds."))

    // MARK: - Hormones

    static let tryptophanToMelatonin = Pathway(
        id: "trp-melatonin", title: "From Turkey to Dreamland",
        subtitle: "Tryptophan → Serotonin → Melatonin", family: .hormones, emoji: "🌙",
        steps: [
            PathwayStep(.mouth, "tryptophan", "Essential arrival",
                        "Trip Tryptophan arrives inside protein from eggs, cheese or pumpkin seeds. He's essential: your body can't make him, so he must come from food."),
            PathwayStep(.bloodstream, "tryptophan", "Race to the brain",
                        "Trip must cross the blood-brain barrier, but other amino acids compete for the same door. After a carb snack, insulin moves competitors into muscles, giving Trip a better shot.",
                        ["Insulin 🔑", "LAT1 door 🚪"]),
            PathwayStep(.brain, "fivehtp", "Add an -OH!",
                        "Tryptophan hydroxylase, an iron-powered enzyme, adds an -OH group to Trip. He becomes Hattie 5-HTP. This slow step controls how much serotonin gets made.",
                        ["Iron 🧲", "BH4 helper", "Oxygen 💨"]),
            PathwayStep(.brain, "serotonin", "Snip! Serotonin!",
                        "An enzyme using vitamin B6 snips off a CO₂. Hattie becomes Sera Serotonin, a messenger for mood, calm and sleep.",
                        ["Vitamin B6 🔧"]),
            PathwayStep(.smallIntestine, "serotonin", "Gut secret",
                        "Surprise! About 90% of your serotonin is made by special cells in your gut, where it helps food keep moving along.",
                        ["Gut enterochromaffin cells 🧫"]),
            PathwayStep(.brain, "melatonin", "Lights out",
                        "When your eyes sense darkness, the pineal gland adds an acetyl group and a methyl group to Sera. She becomes Mel Melatonin, your body's bedtime signal.",
                        ["Darkness 🌙", "Methyl group (B12 + folate) 🧬", "Acetyl-CoA 🔀"]),
        ],
        check: QuizQuestion("Which vitamin helps turn 5-HTP into serotonin?",
                            "Vitamin B6",
                            ["Vitamin C", "Vitamin A", "Vitamin K"],
                            "The enzyme that snips 5-HTP into serotonin uses vitamin B6 as its helper."))

    static let tyrosineSuperstars = Pathway(
        id: "tyrosine-superstars", title: "Tyrosine's Hormone Superstars",
        subtitle: "Phenylalanine → Dopamine → Adrenaline", family: .hormones, emoji: "🎢",
        steps: [
            PathwayStep(.liver, "phenylalanine", "The parent molecule",
                        "Phil Phenylalanine, an essential amino acid, reaches the liver. An iron enzyme with helper BH4 adds an -OH group to make Ty Tyrosine.",
                        ["Iron 🧲", "BH4 helper"]),
            PathwayStep(.bloodstream, "tyrosine", "Many costumes",
                        "Ty travels to the brain and the adrenal glands. Depending on the cell, he can become dopamine, adrenaline, thyroid hormone or melanin pigment!",
                        ["Blood 🩸"]),
            PathwayStep(.brain, "ldopa", "Step 1: L-DOPA",
                        "Tyrosine hydroxylase, another iron enzyme, adds a second -OH. Ty becomes Lulu L-DOPA. This is the slow, controlling step.",
                        ["Iron 🧲", "BH4 helper", "Oxygen 💨"]),
            PathwayStep(.brain, "dopamine", "Step 2: Dopamine",
                        "Vitamin B6 helps snip off a CO₂, and Lulu becomes Dex Dopamine, the brain's motivation and movement messenger.",
                        ["Vitamin B6 🔧"]),
            PathwayStep(.adrenal, "norepinephrine", "Step 3: Noradrenaline",
                        "In the adrenal glands and some nerves, an enzyme powered by copper and vitamin C adds another -OH. Dex becomes Nora Noradrenaline. Alert!",
                        ["Copper 🪙", "Vitamin C 🍊"]),
            PathwayStep(.adrenal, "adrenaline", "Step 4: Adrenaline!",
                        "Finally, a methyl group (recycled with help from B12 and folate) is added. Nora becomes Addie Adrenaline: heart racing, fight or flight!",
                        ["Methyl group (SAM) 🧬", "Cortisol boost ⏰"]),
        ],
        check: QuizQuestion("Which two helpers turn dopamine into noradrenaline?",
                            "Copper and vitamin C",
                            ["Iodine and selenium", "Calcium and vitamin D", "Zinc and vitamin A"],
                            "Dopamine beta-hydroxylase contains copper and uses vitamin C to add an -OH group."))

    static let thyroidFire = Pathway(
        id: "thyroid-fire", title: "Thyroid Fire",
        subtitle: "Iodine + Tyrosine → T4 → T3", family: .minerals, emoji: "🔥",
        steps: [
            PathwayStep(.mouth, "iodine", "Salty start",
                        "Ida Iodine arrives in iodized salt, seafood or dairy.",
                        ["Iodized salt 🧂"]),
            PathwayStep(.smallIntestine, "iodine", "Absorbed as iodide",
                        "Ida is absorbed quickly from the gut into the blood in a form called iodide."),
            PathwayStep(.thyroid, "iodine", "Captured!",
                        "The butterfly-shaped thyroid gland in your neck uses a special pump to trap iodide from the blood.",
                        ["Sodium-iodide pump 🚪"]),
            PathwayStep(.thyroid, "tyrosine", "Stick it on",
                        "Tyrosines sit on a giant protein called thyroglobulin. The enzyme thyroid peroxidase, which contains heme iron, sticks iodine atoms onto them.",
                        ["Thyroid peroxidase (iron) 🧲", "Hydrogen peroxide 🫧"]),
            PathwayStep(.thyroid, "t4", "Four iodines",
                        "Two iodine-coated tyrosines join together. The result is Tate T4 with four iodine atoms, the main hormone the thyroid releases.",
                        ["TSH signal from the brain 📣"]),
            PathwayStep(.liver, "t3", "Selenium switch",
                        "In the liver and other tissues, a selenium-powered deiodinase pops off one iodine. Tate becomes Tia T3, the active form!",
                        ["Selenium ✨"]),
            PathwayStep(.cell, "t3", "Turn up the heat",
                        "Tia enters cell nuclei and switches on genes that build more mitochondria, burn more fuel and make body heat.",
                        ["Thyroid receptor 🔐"]),
        ],
        check: QuizQuestion("What does selenium do for thyroid hormone?",
                            "Helps turn T4 into active T3",
                            ["Adds iodine to tyrosine", "Makes cholesterol", "Stores T4 in bones"],
                            "Deiodinase enzymes contain selenium and remove one iodine from T4 to make T3."))

    static let cholesterolFamily = Pathway(
        id: "cholesterol-family", title: "Cholesterol's Hormone Family",
        subtitle: "Cholesterol → Cortisol, Testosterone, Estradiol", family: .hormones, emoji: "👑",
        steps: [
            PathwayStep(.liver, "cholesterol", "Made at home",
                        "Coco Cholesterol is mostly made by the liver from acetyl-CoA, and food adds a bit more. She's the parent of every steroid hormone.",
                        ["Acetyl-CoA 🔀", "HMG-CoA reductase ⚙️"]),
            PathwayStep(.bloodstream, "cholesterol", "Delivery by LDL",
                        "Coco rides in LDL particles through the blood to the adrenal glands, ovaries and testes.",
                        ["LDL carrier 🚐"]),
            PathwayStep(.adrenal, "pregnenolone", "Snip the tail",
                        "Inside mitochondria, an iron-heme enzyme snips off Coco's side tail. Meet Penny Pregnenolone, mother of all steroids!",
                        ["Iron (heme enzyme) 🧲", "StAR transporter 🚪"]),
            PathwayStep(.adrenal, "progesterone", "Reshape a ring",
                        "Another enzyme rearranges one of Penny's rings. She becomes Paige Progesterone.",
                        ["Vitamin B3 (NAD⁺) 🔥"]),
            PathwayStep(.adrenal, "cortisol", "Stress & wake-up hormone",
                        "In the adrenal glands, a series of iron-heme enzymes add -OH groups. Out comes Cora Cortisol, who raises blood sugar and helps you handle stress.",
                        ["Iron (heme enzymes) 🧲", "ACTH signal from the brain 📣"]),
            PathwayStep(.reproductive, "testosterone", "A growing-up hormone",
                        "In the testes and ovaries, steroid enzymes build Toby Testosterone, who helps build muscle and bone.",
                        ["Iron (heme enzymes) 🧲", "Zinc helps 🛡️"]),
            PathwayStep(.reproductive, "estradiol", "Aromatase magic",
                        "Aromatase turns one of Toby's rings into a flat, aromatic ring. Toby becomes Esme Estradiol! Everyone needs both hormones, just in different amounts.",
                        ["Aromatase ⚙️"]),
        ],
        check: QuizQuestion("Which molecule is the starting material for steroid hormones?",
                            "Cholesterol",
                            ["Glucose", "Tryptophan", "Iodine"],
                            "Cortisol, testosterone, estradiol and even vitamin D are all built from cholesterol."))

    // MARK: - Vitamins & minerals

    static let sunshineVitaminD = Pathway(
        id: "sunshine-d", title: "Sunshine to Strong Bones",
        subtitle: "Sunlight → Vitamin D → Calcitriol", family: .vitamins, emoji: "☀️",
        steps: [
            PathwayStep(.skin, "cholesterol", "Waiting in the skin",
                        "A cholesterol cousin called 7-dehydrocholesterol waits in your skin cells."),
            PathwayStep(.skin, "vitD", "Sunbeam split!",
                        "When UVB sunlight hits, it breaks open one of the rings. Sunny D (vitamin D3) is born! You can also get her from fish, eggs and fortified milk.",
                        ["UVB sunlight ☀️"]),
            PathwayStep(.liver, "calcidiol", "Liver upgrade",
                        "The liver adds an -OH group. Sunny becomes Dee Calcidiol, the storage form that doctors measure in blood tests.",
                        ["25-hydroxylase ⚙️", "Magnesium 🌿"]),
            PathwayStep(.kidney, "calcitriol", "Kidney activation",
                        "The kidneys add one more -OH to make Trixie Calcitriol, the active vitamin D hormone.",
                        ["1-alpha-hydroxylase ⚙️", "Magnesium 🌿", "PTH signal 📣"]),
            PathwayStep(.smallIntestine, "calcium", "Calcium call",
                        "Trixie switches on genes in gut cells that build calcium doors. Now Cal Calcium gets absorbed much better!",
                        ["Calcitriol 🏗️"]),
            PathwayStep(.bones, "calcium", "Build strong bones",
                        "Calcium, phosphate and magnesium build hard bone crystals. Vitamin K helps put calcium where it belongs.",
                        ["Phosphate", "Magnesium 🌿", "Vitamin K 🥬"]),
        ],
        check: QuizQuestion("Where is vitamin D turned into its active hormone, calcitriol?",
                            "In the kidneys",
                            ["In the stomach", "In the skin", "In the lungs"],
                            "Skin makes D3, the liver makes calcidiol, and the kidneys make active calcitriol."))

    static let ironMission = Pathway(
        id: "iron-mission", title: "Iron's Oxygen Mission",
        subtitle: "Iron → Heme → Hemoglobin", family: .minerals, emoji: "🩸",
        steps: [
            PathwayStep(.mouth, "iron", "Two kinds of iron",
                        "Ferro Iron arrives two ways: heme iron from meat (easy to absorb) and non-heme iron from beans and spinach (trickier)."),
            PathwayStep(.stomach, "vitC", "Vitamin C boost",
                        "Stomach acid and Cici Vitamin C change plant iron from Fe³⁺ to Fe²⁺, the form your gut can absorb. Orange slices with beans make a power combo!",
                        ["Stomach acid 🧪", "Vitamin C 🍊"]),
            PathwayStep(.smallIntestine, "iron", "Picky gatekeeper",
                        "Iron is absorbed at the start of the small intestine. Your body is careful: it only lets in about as much iron as it needs.",
                        ["DMT1 door 🚪", "Copper (hephaestin) 🪙"]),
            PathwayStep(.bloodstream, "iron", "Taxi ride",
                        "Free iron is too reactive to float around, so Ferro rides a protein taxi called transferrin to the bone marrow.",
                        ["Transferrin 🚖"]),
            PathwayStep(.bones, "glycine", "Ring building begins",
                        "In young red blood cells, Gigi Glycine joins succinyl-CoA with help from vitamin B6. This starts building a big ring.",
                        ["Vitamin B6 🔧", "Succinyl-CoA"]),
            PathwayStep(.bones, "heme", "Snap in the jewel",
                        "Eight of those building blocks later, the ring is ready. An enzyme called ferrochelatase snaps Ferro into the center. Meet Hema Heme!",
                        ["Ferrochelatase 💍", "Iron 🧲"]),
            PathwayStep(.bones, "hemoglobin", "Assemble the truck",
                        "Four hemes join four globin protein chains to make Hugo Hemoglobin. B12 and folate help the red blood cells divide properly.",
                        ["Globin proteins", "Vitamin B12 🩸", "Folate 🥬"]),
            PathwayStep(.bloodstream, "hemoglobin", "Oxygen delivery!",
                        "Hugo grabs oxygen in the lungs and delivers it to mitochondria everywhere. A red blood cell makes this trip for about 120 days.",
                        ["Oxygen 💨"]),
        ],
        check: QuizQuestion("Which vitamin helps you absorb iron from plants?",
                            "Vitamin C",
                            ["Vitamin D", "Vitamin K", "Vitamin E"],
                            "Vitamin C converts plant iron into the Fe²⁺ form your gut can absorb."))

    static let insulinFromFood = Pathway(
        id: "insulin-from-food", title: "Insulin: A Hormone Made from Food",
        subtitle: "Amino acids → Proinsulin → Insulin", family: .hormones, emoji: "🔑",
        steps: [
            PathwayStep(.smallIntestine, "aminoacid", "Building blocks arrive",
                        "Ami Amino and friends, freed from protein foods, travel through the blood to the pancreas."),
            PathwayStep(.pancreas, "ribosome", "Read the insulin recipe",
                        "Beta cells in the pancreas copy the insulin gene into mRNA. Ribby Ribosome links amino acids into one long chain.",
                        ["DNA → mRNA 📜", "Ribosome 🏭"]),
            PathwayStep(.pancreas, "proinsulin", "Fold and lock",
                        "The chain folds into Pria Proinsulin. Cysteine amino acids form three sulfur bridges that lock the shape in place.",
                        ["Sulfur bridges (cysteine) 🌉"]),
            PathwayStep(.pancreas, "insulin", "Unwrap the gift",
                        "Enzymes snip out the middle piece, called C-peptide. What's left is Izzy Insulin: two chains, 51 amino acids in total.",
                        ["Snipping enzymes ✂️"]),
            PathwayStep(.pancreas, "zinc", "Zinc packing",
                        "Six insulins pack around zinc into tidy crystals, stored in tiny bubbles until they're needed.",
                        ["Zinc 🛡️"]),
            PathwayStep(.bloodstream, "insulin", "Meal alarm!",
                        "After a meal, blood glucose rises. Beta cells sense it and release Izzy into the blood within minutes.",
                        ["Glucose sensor ⚡️", "Calcium signal 🦴"]),
            PathwayStep(.muscle, "glucose", "Unlock the doors",
                        "Izzy binds to muscle and fat cells, and GLUT4 doors move to the surface. Gus Glucose rushes in and blood sugar returns to normal.",
                        ["Insulin receptor 🔐", "GLUT4 door 🚪"]),
        ],
        check: QuizQuestion("What is insulin made from?",
                            "Amino acids",
                            ["Cholesterol", "Fatty acids", "Iodine"],
                            "Insulin is a protein hormone: a chain of 51 amino acids."))

    // MARK: - Energy

    static let atpPowerPlant = Pathway(
        id: "atp-power-plant", title: "The ATP Power Plant",
        subtitle: "Acetyl-CoA → Krebs cycle → ATP", family: .energy, emoji: "🔋",
        steps: [
            PathwayStep(.mitochondria, "mito", "Welcome to the powerhouse",
                        "Dr. Mito here! Carbs, fats and proteins all get broken down into one molecule that enters my furnace..."),
            PathwayStep(.mitochondria, "acetylcoa", "The Krebs cycle",
                        "Acey Acetyl-CoA joins a molecule called oxaloacetate to make citrate, and the Krebs cycle spins. Each turn releases 2 CO₂ that you breathe out.",
                        ["Vitamin B1", "Vitamin B2", "Vitamin B3", "Vitamin B5", "Magnesium 🌿"]),
            PathwayStep(.mitochondria, "nadh", "Electron pickup",
                        "Each turn loads up electron carriers: Nadia NADH (from vitamin B3) and FADH₂ (from vitamin B2) grab high-energy electrons.",
                        ["Vitamin B3 🔥", "Vitamin B2"]),
            PathwayStep(.mitochondria, "nadh", "Electron relay race",
                        "Nadia delivers electrons to the electron transport chain. They hop through iron-sulfur clusters, CoQ10 and copper centers, pumping protons across a membrane.",
                        ["Iron-sulfur clusters 🧲", "CoQ10", "Copper 🪙"]),
            PathwayStep(.mitochondria, "oxygen", "The final catch",
                        "At the end of the chain, Ozzy Oxygen catches the electrons and grabs hydrogen to make water. That's why you need to breathe!",
                        ["Cytochrome oxidase (iron + copper)"]),
            PathwayStep(.mitochondria, "atp", "Spin the turbine!",
                        "Protons rush back through ATP synthase, a real spinning molecular motor! Each turn recharges ADP into Ace ATP, who teams up with magnesium.",
                        ["ATP synthase ⚙️", "Magnesium 🌿"]),
            PathwayStep(.muscle, "atp", "Spend the energy",
                        "Ace powers muscle contractions, nerve signals and building new proteins. You recycle about your own body weight in ATP every day!",
                        ["Myosin motors 💪"]),
        ],
        check: QuizQuestion("What catches electrons at the end of the electron transport chain?",
                            "Oxygen",
                            ["Glucose", "Calcium", "Insulin"],
                            "Oxygen accepts the electrons and becomes water, keeping the ATP assembly line moving."))
}
